# source 'https://cdn.cocoapods.org/'
# install! 'cocoapods', :generate_multiple_pod_projects => true
use_frameworks!
platform :ios, '10.0'


target 'ScanCode_Example' do
  pod 'ScanCode', :path => '../'
end
